# run from workspace root

FROM node:lts

RUN apt-get update && \
apt-get install -y protobuf-compiler &&\
npm install -g npm@latest

WORKDIR /gf-svc-poc
COPY ./shared /gf-svc-poc/shared
COPY ./frontend /gf-svc-poc/frontend

WORKDIR /gf-svc-poc/shared
RUN npm ci
RUN npm run build

WORKDIR /gf-svc-poc/frontend
RUN npm ci
RUN npm run build

EXPOSE 30080

CMD [ "npm", "run", "serve" ]
