version: '3'

services:
  backend-db:
    build:
      context: .
      dockerfile: ./backend/Dockerfile-backend-db
    image: gf-svc-poc-backend-db
    container_name: backend-db
    expose:
      - '5432'

  backend-svc:
    build:
      context: .
      dockerfile: ./backend/Dockerfile-backend-svc
    image: gf-svc-poc-backend-svc
    container_name: backend-svc
    depends_on:
      - backend-db
    ports:
      - '30000:30000'

  gxp-db:
    build:
      context: .
      dockerfile: ./gxp/Dockerfile-gxp-db
    image: gf-svc-poc-gxp-db
    container_name: gxp-db
    expose:
      - '5432'

  gxp-svc:
    build:
      context: .
      dockerfile: ./gxp/Dockerfile-gxp-svc
    image: gf-svc-poc-gxp-svc
    container_name: gxp-svc
    expose:
      - '30002'
    depends_on:
      - gxp-db

  eventlog-db:
    build:
      context: .
      dockerfile: ./eventlog/Dockerfile-eventlog-db
    image: gf-svc-poc-eventlog-db
    container_name: eventlog-db
    expose:
      - '5432'

  eventlog-svc:
    build:
      context: .
      dockerfile: ./eventlog/Dockerfile-eventlog-svc
    image: gf-svc-poc-eventlog-svc
    container_name: eventlog-svc
    depends_on:
      - eventlog-db

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile-frontend
    image: gf-svc-poc-frontend
    container_name: frontend
    ports:
      - '30080:30080'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    expose:
      - '15672'
      - '5672'
