# run from workspace root

FROM node:latest

RUN apt-get update && \
apt-get install -y protobuf-compiler &&\
npm install -g npm@latest

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

WORKDIR /gf-svc-poc
COPY . .

WORKDIR /gf-svc-poc/shared
RUN yarn install
RUN yarn build

WORKDIR /gf-svc-poc/eventlog
RUN yarn install
RUN yarn build

ENTRYPOINT ["/usr/wait-for-it.sh", "eventlog-db:5432", "--", "/usr/wait-for-it.sh", "rabbitmq:5672", "--"]

CMD ["node", "dist/index.js"]
