# run from workspace root

FROM node:latest

RUN apt-get update && \
apt-get install -y protobuf-compiler &&\
npm install -g npm@latest

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

WORKDIR /gf-svc-poc
COPY ./shared /gf-svc-poc/shared
COPY ./eventlog /gf-svc-poc/eventlog

WORKDIR /gf-svc-poc/shared
RUN npm ci
RUN npm run build

WORKDIR /gf-svc-poc/eventlog
RUN npm ci
RUN npm run build

ENTRYPOINT ["/usr/wait-for-it.sh", "eventlog-db:5432", "--", "/usr/wait-for-it.sh", "rabbitmq:5672", "--"]

CMD ["node", "dist/index.js"]
