# run from workspace root

FROM node:latest

RUN apt-get update && \
apt-get install -y protobuf-compiler &&\
npm install -g npm@latest

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

WORKDIR /gf-svc-poc
COPY . .

WORKDIR /gf-svc-poc/shared
RUN yarn install
RUN yarn build

WORKDIR /gf-svc-poc/gxp
RUN yarn install
RUN yarn build

EXPOSE 30002

ENTRYPOINT ["/usr/wait-for-it.sh", "gxp-db:5432", "--", "/usr/wait-for-it.sh", "rabbitmq:5672", "--"]

CMD ["yarn", "start"]
