# run from workspace root

FROM node:lts

RUN apt-get update && \
apt-get install -y protobuf-compiler &&\
npm install -g npm@latest

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/wait-for-it.sh
RUN chmod +x /usr/wait-for-it.sh

WORKDIR /gf-svc-poc
COPY ./shared /gf-svc-poc/shared
COPY ./gxp /gf-svc-poc/gxp

WORKDIR /gf-svc-poc/shared
RUN npm ci
RUN npm run build

WORKDIR /gf-svc-poc/gxp
RUN npm ci
RUN npm run build

EXPOSE 30002

ENTRYPOINT ["/usr/wait-for-it.sh", "gxp-postgres:5432", "--", "/usr/wait-for-it.sh", "rabbitmq:5672", "--"]

CMD ["node", "dist/index.js"]
